name: CI

on: [push]

jobs:
  setup-otp:
    runs-on: ubuntu-latest
    name: A job to setup otp
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup OTP action step
        uses: ./ # Uses an action in the root directory
        id: setup-otp
        with:
          otp-version: "22.3"
      - name: Show self otp version to check the otp setuped correctly
        # Show which erl command and otp major version. If the setup failed following command will also fail.
        run: |
          which erl
          erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
